<?php

?>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">


<title>scandroid</title>

    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    
    <script src="/scandroid/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="/scandroid/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/scandroid/css/styles.css">
    <link rel="stylesheet" href="/scandroid/css/font-awesome.min.css">
    <link rel="icon" type="image/ico" href="/scandroid/images/favicon.ico">


</head>
<body>

<div class="container" style="padding:40px 0; margin-bottom:0;">
<div class="wrapper">

<a href="/scandroid/index.php"><img src="/scandroid/images/BannerLogo2.jpg" id="Logo-small" alt="scandroid"></a>
   
  

  <div class="margin-top-1" style="clear:both;">
    <ul class="nav nav-pills">
      <li>
        <a href="/scandroid/about/about.php">
          About</a>
      </li>
      <li>
        <a href="/scandroid/about/team.php">
          Team</a>
      </li>
      <li>
        <a href="/scandroid/about/credits.php">
          Credits</a>
      </li>
      <li>
        <a href="/scandroid/about/terms.php">
          ToS</a>
      </li>
      <li>
        <a href="/scandroid/about/privacy.php">
          Privacy</a>
      </li>
      <li class="active">
        <a href="/scandroid/about/usage.php">
          Usage</a>
      </li>
      <li>
        <a href="/scandroid/about/contact.php">
          Contact</a>
      </li>
    </ul>
  </div>

    

  <section id="credits" class="ltr">

     <div class="page-header">
      <h1>Best practices</h1>
    </div>

    <div class="rows">
      <div class="span12">
        <p>
          This section details some best practices regarding the use of
          scandroid and its satellite services. It extends other sections in
          this About space and sets rules of fair play when it comes to mine
          and interpret the data generated by scandroid.
        </p>

        <ul>
          <li>
            You should not use the products, services, contents or tools
            provided by scandroid for illicit, unethical or fraudulent
            purposes.
          </li>
          <li>
            You should not to use the products, services, contents or tools
            provided by scandroid in any way that could harm our or associated 
            services, whether that is directly or indirectly.
          </li>
          <li>
            scandroid should only be used as a guide and not for deceptive means 
            to discredit or as bait to prove some concept.
          </li>
          <li>
            The data generated by scandroid should not be used automatically
            as the unique means to blacklist/produce signatures for files. i.e.
            Security vendors should not copy the signatures generated by other
            vendors without any other scrutinizing on their side.
          </li>
          <li>
            scandroid renders information generated by third party products
            (antivirus vendors, URL scanning engines, file characterization
            tools, etc.), those product names are exclusive property of their
            respective brands, hence, use of these names in third party
            products and services will be done at your sole discretion. You
            should ask the corresponding brands for their permission.
          </li>
          <li>
            Abstain from any activity that could damage, overload, harm or
            impede the normal functioning of scandroid's websites.
          </li>
          <li>
            In accordance with applicable legislation, you undertake to refrain
            from illicitly or fraudulently obtaining site/service contents or
            stealing or plagiarising the said contents.
          </li>
          <li>
            You should not submit to scandroid any file that contains personal,
            confidential or sensitive data. Files are shared with antivirus
            vendors and other security industry game players in order to
            strengthen the overall security community know-how and technologies.
            You may not want them to have access to this kind of data.
          </li>
          <li>
            In no event shall you issue any public statement, press release, or
            use scandroid's logo, name or trademark on any customer list or in
            any other manner without our prior written consent in each instance.
          </li>
          <li>
            If you have any doubts as to whether the use of scandroid and its
            satellite services complies with our Terms of Service and our best
            practices, do not hesitate to
            <a href="/en/about/contact.php">contact us</a>
            and request our feedback.
            </li>
        </ul>
      </div>
    </div> 
    


  </section>

  
  
</div><!--end wrapper-->
</div><!--end container-->


<!--footer and Social Media              navbar-bottom controls the color-->
<div class="navbarss navbar-inversess navbarss-fixed-bottom navbar-bottom" sytle="width=100%;" roles="navigation">
    <div class ="containersss">
                
    	<h1 class="text-center navbar-test">Social Media Network</h1>
	<div class="row" style="padding:1% 0;">
	  <!--fontawesome icons-->
	  <div class="col-sm-1 col-sm-offset-2 col-xs-4 text-center navbar-test">
	  <a href="https://github.com/" target="_blank"><i class="fa fa-github fa-4x"></i></a> 
	  </div>
	  <div class="col-sm-1 col-xs-4 text-center navbar-test">
	  <a href="https://foursquare.com/" target="_blank"><i class="fa fa-foursquare fa-4x"></i></a>
	  </div>
	  <div class="col-sm-1 col-xs-4 text-center navbar-test">
	  <a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook fa-4x"></i></a>
	  </div>
	  <div class="col-sm-1 col-xs-4 text-center navbar-test">
	  <a href="https://www.pinterest.com" target="_blank"><i class="fa fa-pinterest fa-4x"></i></a>
	  </div>
	  <div class="col-sm-1 col-xs-4 text-center navbar-test">
	  <a href="https://plus.google.com" target="_blank"><i class="fa fa-google-plus fa-4x"></i></a>
	  </div>
	  <div class="col-sm-1 col-xs-4 text-center navbar-test">
	  <a href="https://twitter.com/?lang=en" target="_blank"><i class="fa fa-twitter fa-4x"></i></a>
	  </div>
	  <div class="col-sm-1 col-xs-4 text-center navbar-test">
	  <a href="https://dribbble.com/" target="_blank"><i class="fa fa-dribbble fa-4x"></i></a>
	  </div>
	  <div class="col-sm-1 col-xs-4 text-center navbar-test">
	  <a href="https://instagram.com/" target="_blank"><i class="fa fa-instagram fa-4x"></i></a>
	  </div>    
	</div><!--/row-->  
	
	<div class="navbar-text pull-left">
            <p>&copy; 2015 scandroid.</p>	
        </div>
        
    </div>
</div>


<div class="navbar navbar-default navbar-fixed-top" >
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" >
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <!--  <a class="navbar-brand" href="#">New scan</a>-->
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/scandroid/index.php">Analyse Another File</a></li>
        <!--<li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>-->
        <li><a href="/scandroid/index.php"><i class="fa fa-home fa-2x pull-right"></i></a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div><!--End Navbar  -->




</body>
</html>